[
  {":0:unknown_function Function ExUnit.Assertions.__timeout__/2 does not exist."},
  {":0:unknown_function Function ExUnit.Assertions.__timeout__/5 does not exist."},
  {":0:unknown_function Function ExUnit.Assertions.assert/2 does not exist."},
  {":0:unknown_function Function ExUnit.Assertions.flunk/1 does not exist."},
  {":0:unknown_function Function ExUnit.Callbacks.__merge__/3 does not exist."},
  {":0:unknown_function Function ExUnit.Callbacks.start_supervised!/1 does not exist."},
  {":0:unknown_function Function ExUnit.Callbacks.start_supervised!/2 does not exist."},
  {":0:unknown_function Function ExUnit.Callbacks.start_supervised/1 does not exist."},
  {":0:unknown_function Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {":0:unknown_function Function Mix.raise/1 does not exist."},
  {":0:unknown_function Function Mix.shell/0 does not exist."},
  {"lib/bitpal_api/channels/invoice_channel.ex:0:guard_fail The guard clause can never succeed."},
  {"lib/bitpal_api/channels/invoice_channel.ex:9:guard_fail The guard clause can never succeed."},
  {"lib/bitpal_doc/link_checker.ex:28:no_return Function has_entry?/1 has no local return."},
  {"lib/bitpal_doc/link_checker.ex:29:call_without_opaque Type mismatch in call without opaque term in member?."},
  {"lib/mix/ci.ex:0:unknown_function Function Mix.raise/1 does not exist."},
  {"lib/mix/ci.ex:0:unknown_function Function Mix.shell/0 does not exist."},
  {"lib/mix/ci.ex:1:callback_info_missing Callback info about the Mix.Task behaviour is not available."},
  {"lib/mix/ci.ex:61:unknown_function Function Mix.raise/1 does not exist."},
  {"lib/mix/ci.ex:66:unknown_function Function Mix.shell/0 does not exist."},
  {"test/bitpal/support/integration_case.ex:0:unknown_function Function ExUnit.Callbacks.__merge__/3 does not exist."},
  {"test/bitpal/support/integration_case.ex:0:unknown_function Function ExUnit.Callbacks.start_supervised!/1 does not exist."},
  {"test/bitpal/support/integration_case.ex:0:unknown_function Function ExUnit.Callbacks.start_supervised!/1 does not exist."},
  {"test/bitpal/support/integration_case.ex:0:unknown_function Function ExUnit.Callbacks.start_supervised/1 does not exist."},
  {"test/bitpal/support/integration_case.ex:0:unknown_function Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"test/bitpal/support/integration_case.ex:11:unknown_function Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"test/bitpal/support/integration_case.ex:1:unknown_function Function ExUnit.Callbacks.__merge__/3 does not exist."},
  {"test/bitpal/support/integration_case.ex:43:unknown_function Function ExUnit.Callbacks.start_supervised!/1 does not exist."},
  {"test/bitpal/support/integration_case.ex:57:unknown_function Function ExUnit.Callbacks.start_supervised/1 does not exist."},
  {"test/bitpal/support/integration_case.ex:75:unknown_function Function ExUnit.Callbacks.start_supervised!/1 does not exist."},
  {"test/bitpal/support/mock_tcp_client.ex:0:unknown_function Function ExUnit.Assertions.assert/2 does not exist."},
  {"test/bitpal/support/mock_tcp_client.ex:0:unknown_function Function ExUnit.Assertions.assert/2 does not exist."},
  {"test/bitpal/support/mock_tcp_client.ex:0:unknown_function Function ExUnit.Callbacks.start_supervised!/1 does not exist."},
  {"test/bitpal/support/mock_tcp_client.ex:122:unknown_function Function ExUnit.Assertions.assert/2 does not exist."},
  {"test/bitpal/support/mock_tcp_client.ex:81:unknown_function Function ExUnit.Assertions.assert/2 does not exist."},
  {"test/bitpal/support/mock_tcp_client.ex:8:unknown_function Function ExUnit.Callbacks.start_supervised!/1 does not exist."},
  {"test/bitpal/support/test_helpers.ex:0:unknown_function Function ExUnit.Assertions.__timeout__/2 does not exist."},
  {"test/bitpal/support/test_helpers.ex:0:unknown_function Function ExUnit.Assertions.__timeout__/5 does not exist."},
  {"test/bitpal/support/test_helpers.ex:0:unknown_function Function ExUnit.Assertions.flunk/1 does not exist."},
  {"test/bitpal/support/test_helpers.ex:18:unknown_function Function ExUnit.Assertions.__timeout__/2 does not exist."},
  {"test/bitpal/support/test_helpers.ex:18:unknown_function Function ExUnit.Assertions.__timeout__/5 does not exist."},
  {"test/bitpal/support/test_helpers.ex:18:unknown_function Function ExUnit.Assertions.flunk/1 does not exist."},
  {"test/bitpal_api/support/channel_case.ex:0:unknown_function Function ExUnit.Callbacks.__merge__/3 does not exist."},
  {"test/bitpal_api/support/channel_case.ex:0:unknown_function Function ExUnit.Callbacks.start_supervised!/1 does not exist."},
  {"test/bitpal_api/support/channel_case.ex:0:unknown_function Function ExUnit.Callbacks.start_supervised!/2 does not exist."},
  {"test/bitpal_api/support/channel_case.ex:0:unknown_function Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"test/bitpal_api/support/channel_case.ex:1:unknown_function Function ExUnit.Callbacks.__merge__/3 does not exist."},
  {"test/bitpal_api/support/channel_case.ex:21:unknown_function Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"test/bitpal_api/support/channel_case.ex:40:unknown_function Function ExUnit.Callbacks.start_supervised!/2 does not exist."},
  {"test/bitpal_api/support/channel_case.ex:41:unknown_function Function ExUnit.Callbacks.start_supervised!/1 does not exist."},
  {"test/bitpal_api/support/conn_case.ex:0:unknown_function Function ExUnit.Callbacks.__merge__/3 does not exist."},
  {"test/bitpal_api/support/conn_case.ex:0:unknown_function Function ExUnit.Callbacks.start_supervised!/1 does not exist."},
  {"test/bitpal_api/support/conn_case.ex:0:unknown_function Function ExUnit.Callbacks.start_supervised!/2 does not exist."},
  {"test/bitpal_api/support/conn_case.ex:0:unknown_function Function ExUnit.Callbacks.start_supervised/1 does not exist."},
  {"test/bitpal_api/support/conn_case.ex:0:unknown_function Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"test/bitpal_api/support/conn_case.ex:1:unknown_function Function ExUnit.Callbacks.__merge__/3 does not exist."},
  {"test/bitpal_api/support/conn_case.ex:25:unknown_function Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"test/bitpal_api/support/conn_case.ex:44:unknown_function Function ExUnit.Callbacks.start_supervised!/2 does not exist."},
  {"test/bitpal_api/support/conn_case.ex:45:unknown_function Function ExUnit.Callbacks.start_supervised!/1 does not exist."},
  {"test/bitpal_live_web/support/channel_case.ex:0:unknown_function Function ExUnit.Callbacks.__merge__/3 does not exist."},
  {"test/bitpal_live_web/support/channel_case.ex:0:unknown_function Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"test/bitpal_live_web/support/conn_case.ex:0:unknown_function Function ExUnit.Callbacks.__merge__/3 does not exist."},
  {"test/bitpal_live_web/support/conn_case.ex:0:unknown_function Function ExUnit.Callbacks.start_supervised!/1 does not exist."},
  {"test/bitpal_live_web/support/conn_case.ex:0:unknown_function Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"test/bitpal_web/support/channel_case.ex:0:unknown_function Function ExUnit.Callbacks.__merge__/3 does not exist."},
  {"test/bitpal_web/support/channel_case.ex:0:unknown_function Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"test/bitpal_web/support/channel_case.ex:1:unknown_function Function ExUnit.Callbacks.__merge__/3 does not exist."},
  {"test/bitpal_web/support/channel_case.ex:20:unknown_function Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"test/bitpal_web/support/conn_case.ex:0:unknown_function Function ExUnit.Callbacks.__merge__/3 does not exist."},
  {"test/bitpal_web/support/conn_case.ex:0:unknown_function Function ExUnit.Callbacks.start_supervised!/1 does not exist."},
  {"test/bitpal_web/support/conn_case.ex:0:unknown_function Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"test/bitpal_web/support/conn_case.ex:1:unknown_function Function ExUnit.Callbacks.__merge__/3 does not exist."},
  {"test/bitpal_web/support/conn_case.ex:20:unknown_function Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"test/bitpal_web/support/conn_case.ex:35:unknown_function Function ExUnit.Callbacks.start_supervised!/1 does not exist."}
]
